// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxRrv45eTTN-5szMD_fwyVQJaEhd6A0w',
    appId: '1:676221233129:web:2df958d0ef89549beb8d78',
    messagingSenderId: '676221233129',
    projectId: 'windsy-solve',
    authDomain: 'windsy-solve.firebaseapp.com',
    databaseURL: 'https://windsy-solve.firebaseio.com',
    storageBucket: 'windsy-solve.appspot.com',
    measurementId: 'G-408255G6LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCCGjpFBqqW-krBaKfdCwcBy2COyP33c',
    appId: '1:676221233129:android:5abbb749474b2925eb8d78',
    messagingSenderId: '676221233129',
    projectId: 'windsy-solve',
    databaseURL: 'https://windsy-solve.firebaseio.com',
    storageBucket: 'windsy-solve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPZM6DdgonMEsvkLZEeOpJv4Sg-qzMR0',
    appId: '1:676221233129:ios:b6776a0fe7d84004eb8d78',
    messagingSenderId: '676221233129',
    projectId: 'windsy-solve',
    databaseURL: 'https://windsy-solve.firebaseio.com',
    storageBucket: 'windsy-solve.appspot.com',
    iosBundleId: 'com.windsy.windsySolve',
  );
}
