import 'package:flutter/material.dart';

class HomeGeneratedReports extends StatelessWidget {
  const HomeGeneratedReports({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return ListView.builder(
      itemCount: 20,
      shrinkWrap: true,
      itemBuilder: (context, index) {
        return ListTile(
          onTap: () {
            print(index);
          },
          leading: Icon(
            Icons.insert_drive_file_rounded,
            size: 24.0,
            color: theme.colorScheme.background,
          ),
          title: Text(
            'Report $index testing this test and checking',
            style: theme.textTheme.titleMedium,
            overflow: TextOverflow.ellipsis,
          ),
          subtitle: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'NC - Wind Turbine Issue',
                style: theme.textTheme.labelMedium,
              ),
              Text(
                'Generated on 12/12/2021',
                style: theme.textTheme.labelSmall,
              ),
              Text(
                'Generated by Felix Wernicke',
                style: theme.textTheme.labelSmall,
              ),
            ],
          ),
          trailing: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              IconButton(
                icon: const Icon(
                  Icons.download_rounded,
                  size: 20.0,
                ),
                onPressed: () {},
              ),
              IconButton(
                icon: const Icon(
                  Icons.delete_forever_rounded,
                  size: 20.0,
                  color: Colors.red,
                ),
                onPressed: () {},
              ),
            ],
          ),
        );
      },
    );
  }
}
